version: "2.2"
services:

  elasticsearch:
    image: elasticsearch:6.6.0

    container_name: elastichost

    ports:
      - "9200:9200"
      - "9300:9300"

    environment:
      - discovery.type=single-node

    volumes:
      # elasticsearch data
      - esdata:/usr/share/elasticsearch/data

      # elasticsearch config
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

      # - ./data:/data

    networks:
      - esnet

  kibana:
    image: kibana:6.6.0

    container_name: kibana

    ports:
      - "5601:5601"

    volumes:
      # kibana config
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

      # - ./data:/data

    networks:
      - esnet


  logstash:
    build:
      context: ./build
      dockerfile: Dockerfile-logstash

    container_name: logstash

    expose:
      - "5044"

    volumes:
      # logstash config
      - ./config/logstash/logstash.yml:/etc/logstash/logstash.yml
      - ./config/logstash/pipelines.yml:/etc/logstash/pipelines.yml
      - ./config/logstash/conf.d:/etc/logstash/conf.d

      # filebeat config
      - ./config/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml

      - ./data:/data

    networks:
      - esnet

  test:
    build:
      context: ./build
      dockerfile: Dockerfile-test

    container_name: test

    volumes:
      - ./config/test:/test
      - ./data:/data

    networks:
      - esnet


volumes:
  esdata:
    driver: local

networks:
  esnet:
