version: "2.2"
services:

  elasticsearch:
    image: elasticsearch:6.6.0

    container_name: elastichost

    ports:
      - "9200:9200"
      - "9300:9300"

    environment:
      - discovery.type=single-node

    volumes:
      - esdata:/usr/share/elasticsearch/data

    networks:
      - esnet

  kibana:
    image: kibana:6.6.0

    container_name: kibana

    ports:
      - "5601:5601"

    # volumes:
    #   - ./contents/kibana/settings:/usr/share/kibana/config

    networks:
      - esnet


  logstash:
    build:
      context: ./build
      dockerfile: Dockerfile-logstash

    container_name: logstash

    expose:
      - "5044"

    volumes:
      - ./contents/logstash/settings:/etc/logstash
      - ./contents/filebeat/config:/etc/filebeat
      - ./data:/data

    networks:
      - esnet

  test:
    build:
      context: ./build
      dockerfile: Dockerfile-test

    container_name: test

    volumes:
      - ./contents/test:/
      - ./data:/data

    networks:
      - esnet


volumes:
  esdata:
    driver: local

networks:
  esnet:
